// File generated by FlutterFire CLI.
// NOTE: This file should be checked into source control and not modified manually.

// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: avoid_classes_with_only_static_members
// ignore_for_file: join_return_with_assignment
// ignore_for_file: prefer_final_locals

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform.
///
/// This file provides default values for all platform-specific configurations.
/// You should replace the placeholder values with your actual Firebase project
/// settings from the Firebase Console.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration
  // Configuração atualizada para checkos-system
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe9QtfTH-pRBVAv0TJpsOrdJ7HYwwTFl8',
    appId: '1:934697110970:web:b5760e7ca182ebd83f2183',
    authDomain: 'checkos-system.firebaseapp.com',
    databaseURL: 'https://checkos-system.firebaseio.com',
    projectId: 'checkos-system',
    storageBucket: 'checkos-system.firebasestorage.app',
    messagingSenderId: '934697110970',
    measurementId: 'G-969DLHS6HS',
  );

  // Android configuration
  // These values are taken from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGd_LI_WOc7HFP5rrtPzMZhEkdcW-oYo',
    appId: '1:934697110970:android:f756af0df77135163f2183',
    databaseURL: 'https://checkos-system.firebaseio.com',
    messagingSenderId: '934697110970',
    projectId: 'checkos-system',
    storageBucket: 'checkos-system.firebasestorage.app',
  );

  // iOS configuration
  // IMPORTANT: Replace these values with your actual Firebase project settings
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Replace with your actual iOS API key
    appId: '1:934697110970:ios:xxxxxxxxxxxxxxxx',
    databaseURL: 'https://checkos-system.firebaseio.com',
    messagingSenderId: '934697110970',
    projectId: 'checkos-system',
    storageBucket: 'checkos-system.firebasestorage.app',
    iosClientId: '934697110970-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com', // Replace with actual iOS Client ID
    iosBundleId: 'com.example.checkos', // Replace with actual iOS Bundle ID
  );

  // macOS configuration (optional - only if needed)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Replace with your actual macOS API key
    appId: '1:934697110970:macos:xxxxxxxxxxxxxxxxxxxxx', // Replace with actual macOS app ID
    databaseURL: 'https://checkos-system.firebaseio.com',
    messagingSenderId: '934697110970',
    projectId: 'checkos-system',
    storageBucket: 'checkos-system.firebasestorage.app',
    iosClientId: '934697110970-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkos',
  );

  // Windows configuration (optional - only if needed)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY', // Replace with your actual Windows API key
    appId: '1:934697110970:windows:xxxxxxxxxxxxxxxxxxxxx', // Replace with actual Windows app ID
    databaseURL: 'https://checkos-system.firebaseio.com',
    messagingSenderId: '934697110970',
    projectId: 'checkos-system',
    storageBucket: 'checkos-system.firebasestorage.app',
  );
}

