// File generated by FlutterFire CLI.
// NOTE: This file should be checked into source control and not modified manually.

// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: avoid_classes_with_only_static_members
// ignore_for_file: join_return_with_assignment
// ignore_for_file: prefer_final_locals

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default Firebase configuration options for the current platform.
///
/// This file provides default values for all platform-specific configurations.
/// You should replace the placeholder values with your actual Firebase project
/// settings from the Firebase Console.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web configuration
  // IMPORTANT: Replace these values with your actual Firebase project settings
  // You can find these in Firebase Console > Project Settings
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'BMSCohXer0F55tShFBtf8V2Jay53RTTsFjd9XUpAdvQlqXE12Vz9xG8MD0Sz9a2Sejb9Ji977jJ_IawW2xJXYlk', // Replace with your actual web API key
    appId: '1:617597131745:web:0a1b2c3d4e5f6g7h8i9j0',
    authDomain: 'checkos-app.firebaseapp.com',
    databaseURL: 'https://checkos-app.firebaseio.com',
    projectId: 'checkos-app',
    storageBucket: 'checkos-app.appspot.com',
    messagingSenderId: '617597131745',
  );

  // Android configuration
  // These values are taken from android/app/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5x2x_1x_2x_2x_2x_2x_2x_2x_2x_2x', // Replace with actual Android API key
    appId: '1:617597131745:android:fd101b57255a34d6b0d0a0',
    databaseURL: 'https://checkos-app.firebaseio.com',
    messagingSenderId: '617597131745',
    projectId: 'checkos-app',
    storageBucket: 'checkos-app.appspot.com',
  );

  // iOS configuration
  // IMPORTANT: Replace these values with your actual Firebase project settings
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Replace with your actual iOS API key
    appId: '1:617597131745:ios:07c48407f64fa1d7b0d0a0',
    databaseURL: 'https://checkos-app.firebaseio.com',
    messagingSenderId: '617597131745',
    projectId: 'checkos-app',
    storageBucket: 'checkos-app.appspot.com',
    iosClientId: '617597131745-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com', // Replace with actual iOS Client ID
    iosBundleId: 'com.example.checkos', // Replace with actual iOS Bundle ID
  );

  // macOS configuration (optional - only if needed)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // Replace with your actual macOS API key
    appId: '1:617597131745:macos:xxxxxxxxxxxxxxxxxxxxx', // Replace with actual macOS app ID
    databaseURL: 'https://checkos-app.firebaseio.com',
    messagingSenderId: '617597131745',
    projectId: 'checkos-app',
    storageBucket: 'checkos-app.appspot.com',
    iosClientId: '617597131745-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com',
    iosBundleId: 'com.example.checkos',
  );

  // Windows configuration (optional - only if needed)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY', // Replace with your actual Windows API key
    appId: '1:617597131745:windows:xxxxxxxxxxxxxxxxxxxxx', // Replace with actual Windows app ID
    databaseURL: 'https://checkos-app.firebaseio.com',
    messagingSenderId: '617597131745',
    projectId: 'checkos-app',
    storageBucket: 'checkos-app.appspot.com',
  );
}

